### ISSUE TITLE
Whitespaces in address?

### ISSUE THREAD

**Issue by rajhub** [jackbowman/email-addresses#15]
It seems whitespaces are allowed in addresses. I received an email into our system with the below "from" address and parsing failed and returned null.

```javascript
var from = '"xxxxxxx, yyy A MAJ USARMY 2 CAV REGT (US)"\n\t<yyy.a.xxxxxxx.mil@mail.mil>\n';

console.log(addrs.parseOneAddress(from)); // returns null
```

**Comment by jackbowman** [comment]
The rules around parsing whitespace in the email RFCs are very particular and strange, so be careful here. I'll explain why this doesn't parse, but for your purposes this might not be helpful. What is your goal? If you're parsing potentially messy and non-spec compliant emails that are nevertheless being sent to you by real mail servers, this library may not be the best fit.

The address `'"xxxxxxx, yyy A MAJ USARMY 2 CAV REGT (US)"\r\n\t<yyy.a.xxxxxxx.mil@mail.mil>'` or `'"xxxxxxx, yyy A MAJ USARMY 2 CAV REGT (US)"\r\n\t<yyy.a.xxxxxxx.mil@mail.mil>\r\n\t'`, etc. will parse.  Why?

For one, newlines in whitespace in an email address must always be "\r\n", never just "\n". Otherwise there is no chance of it parsing. The other recognized whitespace is either space (" ") or tab ("\t"). Newlines can't appear by themselves, which may also seem strange. So "\r\n\t" may be ignored as whitespace, but "\r\n" by itself is not allowed. Pretty arbitrary, huh?
